version: 0.0
os: linux

files:
  - source: /
    destination: /opt/flitecraft-HPD-Integration
    overwrite: true

permissions:
  - object: /opt/flitecraft-HPD-Integration/scripts
    pattern: "**"
    owner: root
    group: root
    mode: 755
    type:
      - file
      - directory

hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 1800
      runas: root
    - location: scripts/install_service.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root


